export const capitalLookup: Record<string, Set<string>> = {
  "A": new Set([
    "abu dhabi",
    "abuja",
    "accra",
    "adamstown",
    "addis ababa",
    "algiers",
    "alofi",
    "amman",
    "amsterdam",
    "andorra la vella",
    "ankara",
    "antananarivo",
    "apia",
    "ashgabat",
    "asmara",
    "astana",
    "asuncion",
    "athens",
    "avarua",
  ]),
  "B": new Set([
    "baghdad",
    "baku",
    "bamako",
    "bandar seri begawan",
    "bangkok",
    "bangui",
    "banjul",
    "basse-terre",
    "basseterre",
    "beijing",
    "beirut",
    "belgrade",
    "belmopan",
    "berlin",
    "bern",
    "bishkek",
    "bissau",
    "bogota",
    "brasilia",
    "bratislava",
    "brazzaville",
    "bridgetown",
    "brussels",
    "bucharest",
    "budapest",
    "buenos aires",
    "bujumbura",
  ]),
  "C": new Set([
    "cairo",
    "canberra",
    "caracas",
    "castries",
    "cayenne",
    "charlotte amalie",
    "chisinau",
    "ciudad de mexico",
    "cockburn town",
    "colombo",
    "conakry",
    "copenhagen",
  ]),
  "D": new Set([
    "dakar",
    "damascus",
    "dhaka",
    "diego garcia",
    "dili",
    "djibouti",
    "dodoma",
    "doha",
    "douglas, isle of man",
    "dublin",
    "dushanbe",
  ]),
  "E": new Set([
    "east jerusalem",
    "el-aaiun",
  ]),
  "F": new Set([
    "flying fish cove",
    "fort-de-france",
    "freetown",
    "funafuti",
  ]),
  "G": new Set([
    "gaborone",
    "george town",
    "georgetown",
    "gibraltar",
    "grytviken",
    "guatemala city",
    "gustavia",
  ]),
  "H": new Set([
    "hagatna",
    "hamilton",
    "hanoi",
    "harare",
    "havana",
    "helsinki",
    "hong kong",
    "honiara",
  ]),
  "I": new Set([
    "islamabad",
  ]),
  "J": new Set([
    "jakarta",
    "jamestown",
    "jerusalem",
    "juba",
  ]),
  "K": new Set([
    "kabul",
    "kampala",
    "kathmandu",
    "khartoum",
    "kigali",
    "kingston",
    "kingstown",
    "kinshasa",
    "kralendijk",
    "kuala lumpur",
    "kuwait city",
    "kyiv",
  ]),
  "L": new Set([
    "libreville",
    "lilongwe",
    "lima",
    "lisbon",
    "ljubljana",
    "lome",
    "london",
    "longyearbyen",
    "luanda",
    "lusaka",
    "luxembourg",
  ]),
  "M": new Set([
    "macao",
    "madrid",
    "majuro",
    "malabo",
    "male",
    "mamoudzou",
    "managua",
    "manama",
    "manila",
    "maputo",
    "mariehamn",
    "marigot",
    "maseru",
    "mata utu",
    "mbabane",
    "melekeok",
    "minsk",
    "mogadishu",
    "monaco",
    "monrovia",
    "montevideo",
    "moroni",
    "moscow",
    "muscat",
  ]),
  "N": new Set([
    "n'djamena",
    "nairobi",
    "nassau",
    "nay pyi taw",
    "new delhi",
    "niamey",
    "nicosia",
    "nouakchott",
    "noumea",
    "nuku'alofa",
    "nuuk",
  ]),
  "O": new Set([
    "oranjestad",
    "oslo",
    "ottawa",
    "ouagadougou",
  ]),
  "P": new Set([
    "pago pago",
    "palikir",
    "panama city",
    "papeete",
    "paramaribo",
    "paris",
    "philipsburg",
    "phnom penh",
    "plymouth",
    "podgorica",
    "port louis",
    "port moresby",
    "port of spain",
    "port vila",
    "port-au-prince",
    "port-aux-francais",
    "porto-novo",
    "prague",
    "praia",
    "pretoria",
    "pristina",
    "pyongyang",
  ]),
  "Q": new Set([
    "quito",
  ]),
  "R": new Set([
    "rabat",
    "reykjavik",
    "riga",
    "riyadh",
    "road town",
    "rome",
    "roseau",
  ]),
  "S": new Set([
    "saint helier",
    "saint-denis",
    "saint-pierre",
    "saipan",
    "san jose",
    "san juan",
    "san marino",
    "san salvador",
    "sanaa",
    "santiago",
    "santo domingo",
    "sao tome",
    "sarajevo",
    "seoul",
    "singapur",
    "skopje",
    "sofia",
    "st peter port",
    "st. george's",
    "st. john's",
    "stanley",
    "stockholm",
    "sucre",
    "suva",
  ]),
  "T": new Set([
    "taipei",
    "tallinn",
    "tarawa",
    "tashkent",
    "tbilisi",
    "tegucigalpa",
    "tehran",
    "the valley",
    "thimphu",
    "tirana",
    "tokyo",
    "torshavn",
    "tripolis",
    "tunis",
  ]),
  "U": new Set([
    "ulan bator",
  ]),
  "V": new Set([
    "vaduz",
    "valletta",
    "vatican city",
    "victoria",
    "vienna",
    "vientiane",
    "vilnius",
  ]),
  "W": new Set([
    "warsaw",
    "washington",
    "wellington",
    "west island",
    "willemstad",
    "windhoek",
  ]),
  "Y": new Set([
    "yamoussoukro",
    "yaounde",
    "yaren",
    "yerevan",
  ]),
  "Z": new Set([
    "zagreb",
  ]),
};
