export const countryLookup: Record<string, Set<string>> = {
  "A": new Set([
    "afghanistan",
    "aland islands",
    "albania",
    "algeria",
    "american samoa",
    "andorra",
    "angola",
    "anguilla",
    "antarctica",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
  ]),
  "B": new Set([
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bonaire, sint eustatius and saba",
    "bosnia and herzegovina",
    "botswana",
    "bouvet island",
    "brazil",
    "british indian ocean territory",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
  ]),
  "C": new Set([
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "cayman islands",
    "central african republic",
    "chad",
    "chile",
    "china",
    "christmas island",
    "cocos (keeling) islands",
    "colombia",
    "comoros",
    "congo",
    "cook islands",
    "costa rica",
    "cote d'ivoire (ivory coast)",
    "croatia",
    "cuba",
    "curacao",
    "cyprus",
    "czech republic",
  ]),
  "D": new Set([
    "democratic republic of the congo",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
  ]),
  "E": new Set([
    "east timor",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
  ]),
  "F": new Set([
    "falkland islands",
    "faroe islands",
    "fiji islands",
    "finland",
    "france",
    "french guiana",
    "french polynesia",
    "french southern territories",
  ]),
  "G": new Set([
    "gabon",
    "gambia the",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guam",
    "guatemala",
    "guernsey and alderney",
    "guinea",
    "guinea-bissau",
    "guyana",
  ]),
  "H": new Set([
    "haiti",
    "heard island and mcdonald islands",
    "honduras",
    "hong kong s.a.r.",
    "hungary",
  ]),
  "I": new Set([
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
  ]),
  "J": new Set([
    "jamaica",
    "japan",
    "jersey",
    "jordan",
  ]),
  "K": new Set([
    "kazakhstan",
    "kenya",
    "kiribati",
    "kosovo",
    "kuwait",
    "kyrgyzstan",
  ]),
  "L": new Set([
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
  ]),
  "M": new Set([
    "macau s.a.r.",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "man (isle of)",
    "marshall islands",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "myanmar",
  ]),
  "N": new Set([
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new caledonia",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "norfolk island",
    "north korea",
    "north macedonia",
    "northern mariana islands",
    "norway",
  ]),
  "O": new Set([
    "oman",
  ]),
  "P": new Set([
    "pakistan",
    "palau",
    "palestinian territory occupied",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "pitcairn island",
    "poland",
    "portugal",
    "puerto rico",
  ]),
  "Q": new Set([
    "qatar",
  ]),
  "R": new Set([
    "reunion",
    "romania",
    "russia",
    "rwanda",
  ]),
  "S": new Set([
    "saint helena",
    "saint kitts and nevis",
    "saint lucia",
    "saint pierre and miquelon",
    "saint vincent and the grenadines",
    "saint-barthelemy",
    "saint-martin (french part)",
    "samoa",
    "san marino",
    "sao tome and principe",
    "saudi arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leone",
    "singapore",
    "sint maarten (dutch part)",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south georgia",
    "south korea",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "svalbard and jan mayen islands",
    "swaziland",
    "sweden",
    "switzerland",
    "syria",
  ]),
  "T": new Set([
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "the bahamas",
    "togo",
    "tokelau",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos islands",
    "tuvalu",
  ]),
  "U": new Set([
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "united states minor outlying islands",
    "uruguay",
    "uzbekistan",
  ]),
  "V": new Set([
    "vanuatu",
    "vatican city state (holy see)",
    "venezuela",
    "vietnam",
    "virgin islands (british)",
    "virgin islands (us)",
  ]),
  "W": new Set([
    "wallis and futuna islands",
    "western sahara",
  ]),
  "Y": new Set([
    "yemen",
  ]),
  "Z": new Set([
    "zambia",
    "zimbabwe",
  ]),
};
