export const currencyLookup: Record<string, Set<string>> = {
  "A": new Set([
    "aad",
    "aed",
    "afghan afghani",
    "afn",
    "albanian lek",
    "algerian dinar",
    "all",
    "amd",
    "ang",
    "angolan kwanza",
    "antarctican dollar",
    "aoa",
    "argentine peso",
    "armenian dram",
    "ars",
    "aruban florin",
    "aud",
    "australian dollar",
    "awg",
    "azerbaijani manat",
    "azn",
  ]),
  "B": new Set([
    "bahamian dollar",
    "bahraini dinar",
    "bam",
    "bangladeshi taka",
    "barbadian dollar",
    "bbd",
    "bdt",
    "belarusian ruble",
    "belize dollar",
    "bermudian dollar",
    "bgn",
    "bhd",
    "bhutanese ngultrum",
    "bif",
    "bmd",
    "bnd",
    "bob",
    "bolivar",
    "bolivian boliviano",
    "bosnia and herzegovina convertible mark",
    "botswana pula",
    "brazilian real",
    "british pound",
    "brl",
    "brunei dollar",
    "bsd",
    "btn",
    "bulgarian lev",
    "burmese kyat",
    "burundian franc",
    "bwp",
    "byn",
    "bzd",
  ]),
  "C": new Set([
    "cad",
    "cambodian riel",
    "canadian dollar",
    "cape verdean escudo",
    "cayman islands dollar",
    "cdf",
    "central african cfa franc",
    "cfp franc",
    "chf",
    "chilean peso",
    "chinese yuan",
    "clp",
    "cny",
    "colombian peso",
    "comorian franc",
    "congolese franc",
    "cook islands dollar",
    "cop",
    "costa rican colon",
    "crc",
    "croatian kuna",
    "cuban peso",
    "cup",
    "cve",
    "czech koruna",
    "czk",
  ]),
  "D": new Set([
    "danish krone",
    "denar",
    "djf",
    "djiboutian franc",
    "dkk",
    "dobra",
    "dominican peso",
    "dop",
    "dzd",
  ]),
  "E": new Set([
    "east caribbean dollar",
    "eastern caribbean dollar",
    "egp",
    "egyptian pound",
    "eritrean nakfa",
    "ern",
    "etb",
    "ethiopian birr",
    "eur",
    "euro",
  ]),
  "F": new Set([
    "falkland islands pound",
    "fijian dollar",
    "fjd",
    "fkp",
  ]),
  "G": new Set([
    "gambian dalasi",
    "gbp",
    "gel",
    "georgian lari",
    "ghanaian cedi",
    "ghs",
    "gibraltar pound",
    "gip",
    "gmd",
    "gnf",
    "gtq",
    "guatemalan quetzal",
    "guinean franc",
    "guyanese dollar",
    "gyd",
  ]),
  "H": new Set([
    "haitian gourde",
    "hkd",
    "hnl",
    "honduran lempira",
    "hong kong dollar",
    "hrk",
    "htg",
    "huf",
    "hungarian forint",
  ]),
  "I": new Set([
    "icelandic krona",
    "idr",
    "ils",
    "indian rupee",
    "indonesian rupiah",
    "inr",
    "iqd",
    "iranian rial",
    "iraqi dinar",
    "irr",
    "isk",
    "israeli new shekel",
  ]),
  "J": new Set([
    "jamaican dollar",
    "japanese yen",
    "jmd",
    "jod",
    "jordanian dinar",
    "jpy",
  ]),
  "K": new Set([
    "kazakhstani tenge",
    "kenyan shilling",
    "kes",
    "kgs",
    "khr",
    "kmf",
    "kpw",
    "krw",
    "kuwaiti dinar",
    "kwd",
    "kyd",
    "kyrgyzstani som",
    "kzt",
  ]),
  "L": new Set([
    "lak",
    "lao kip",
    "lbp",
    "lebanese pound",
    "lesotho loti",
    "liberian dollar",
    "libyan dinar",
    "lilangeni",
    "lkr",
    "lrd",
    "lsl",
    "lyd",
  ]),
  "M": new Set([
    "macanese pataca",
    "mad",
    "malagasy ariary",
    "malawian kwacha",
    "malaysian ringgit",
    "maldivian rufiyaa",
    "mauritanian ouguiya",
    "mauritian rupee",
    "mdl",
    "mexican peso",
    "mga",
    "mkd",
    "mmk",
    "mnt",
    "moldovan leu",
    "mongolian togrog",
    "mop",
    "moroccan dirham",
    "mozambican metical",
    "mro",
    "mur",
    "mvr",
    "mwk",
    "mxn",
    "myr",
    "mzn",
  ]),
  "N": new Set([
    "nad",
    "namibian dollar",
    "nepalese rupee",
    "netherlands antillean guilder",
    "new taiwan dollar",
    "new zealand dollar",
    "ngn",
    "nicaraguan cordoba",
    "nigerian naira",
    "nio",
    "nok",
    "north korean won",
    "norwegian krone",
    "npr",
    "nzd",
  ]),
  "O": new Set([
    "omani rial",
    "omr",
  ]),
  "P": new Set([
    "pab",
    "pakistani rupee",
    "panamanian balboa",
    "papua new guinean kina",
    "paraguayan guarani",
    "pen",
    "peruvian sol",
    "pgk",
    "philippine peso",
    "php",
    "pkr",
    "pln",
    "polish zloty",
    "pyg",
  ]),
  "Q": new Set([
    "qar",
    "qatari riyal",
  ]),
  "R": new Set([
    "romanian leu",
    "ron",
    "rsd",
    "rub",
    "russian ruble",
    "rwandan franc",
    "rwf",
  ]),
  "S": new Set([
    "saint helena pound",
    "samoan tala",
    "sar",
    "saudi riyal",
    "sbd",
    "scr",
    "sdg",
    "sek",
    "serbian dinar",
    "seychellois rupee",
    "sgd",
    "shp",
    "sierra leonean leone",
    "singapore dollar",
    "sll",
    "solomon islands dollar",
    "somali shilling",
    "sos",
    "south african rand",
    "south sudanese pound",
    "srd",
    "sri lankan rupee",
    "ssp",
    "std",
    "sudanese pound",
    "surinamese dollar",
    "swedish krona",
    "swiss franc",
    "syp",
    "syrian pound",
    "szl",
  ]),
  "T": new Set([
    "tajikistani somoni",
    "tanzanian shilling",
    "thai baht",
    "thb",
    "tjs",
    "tmt",
    "tnd",
    "tongan paʻanga",
    "top",
    "trinidad and tobago dollar",
    "try",
    "ttd",
    "tunisian dinar",
    "turkish lira",
    "turkmenistan manat",
    "twd",
    "tzs",
  ]),
  "U": new Set([
    "uah",
    "ugandan shilling",
    "ugx",
    "ukrainian hryvnia",
    "united arab emirates dirham",
    "united states dollar",
    "uruguayan peso",
    "us dollar",
    "usd",
    "uyu",
    "uzbekistani soʻm",
    "uzs",
  ]),
  "V": new Set([
    "vanuatu vatu",
    "ves",
    "vietnamese dong",
    "vnd",
    "vuv",
  ]),
  "W": new Set([
    "west african cfa franc",
    "won",
    "wst",
  ]),
  "X": new Set([
    "xaf",
    "xcd",
    "xof",
    "xpf",
  ]),
  "Y": new Set([
    "yemeni rial",
    "yer",
  ]),
  "Z": new Set([
    "zambian kwacha",
    "zar",
    "zimbabwe dollar",
    "zmw",
    "zwl",
  ]),
};
